In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


#creating 1D array ( 1 dimensional array )
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape) #this will give you (rows,column)


[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [3]:
#converting the 1D array to 2D array
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
array_2d = arr2.reshape((2,5))
print(array_2d)
print(array_2d.shape)
print(array_2d.size)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
10


In [4]:
#creating 2D array 
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr3)
print(type(arr3))
print(arr3.shape)
print(arr3.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
(3, 4)
12


In [5]:
#arr.something() is a method 
#numpy.something() is a function 
#arr.something is a attribute

In [6]:
#generating the values using inbuild functions in numpy

#arange
print(np.arange(1,11).reshape(2,5),'\n')

#zeros 
print(np.zeros((4,4)),'\n')

#ones 
print(np.ones((3,3),'\n'))

#eye ( identity matrix )
print(np.eye(3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#numpy attributes 
arr4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

#shape 
print(arr4.shape)

#size 
print(arr4.size)

#ndim
print(arr4.ndim)

(2, 5)
10
2


In [8]:
#numpy vectorized operations ( element wise operation will happen in numpy )

arr5 = np.array([1,2,3,4])
arr6 = np.array([5,6,7,8])

#addition 
addition = arr5+arr6
print(addition)

subtraction = arr5-arr6
print(subtraction)

multiplication = arr5*arr6
print(multiplication)

division = arr5/arr6
print(division)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [9]:
#universal functions 

arr = np.array([1,2,3,4,5])

#sqrt root 
print(np.sqrt(arr))

#exponent (e to power of )
print(np.exp(arr))

#sin 
print(np.sin(arr))

#natural log 
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [23]:
#slicing operations on array 

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"array: {arr},\n")

print(arr[0],end="\n\n") #this will give you first array

print(arr[0][0],end="\n\n") #this will give you 1 value
print(arr[1:],end="\n\n") #this will give you the values from 1st index values
print(arr.shape,end="\n\n")
print(arr[1:,2:],end="\n\n") #[rows,columns] [[7,8],[11,12]]
print(arr[0:2,2:],end="\n\n")
print(arr[1:,1:3])

array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]],

[1 2 3 4]

1

[[ 5  6  7  8]
 [ 9 10 11 12]]

(3, 4)

[[ 7  8]
 [11 12]]

[[3 4]
 [7 8]]

[[ 6  7]
 [10 11]]


In [24]:
#modify the elements 
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean 
mean =np.mean(data)
print(f"mean: {mean}")

#median 
median = np.median(data)
print(f"median: {median}")

#standard_deviation
standard_deviation = np.std(data)
print(f"standard_deviation: {standard_deviation}")

#variance 
variance = np.var(data)
print(f"variance: {variance}")


mean: 5.5
median: 5.5
standard_deviation: 2.8722813232690143
variance: 8.25


In [28]:
#finding the standardization 
data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
standard_deviation = np.std(data)

standardization = data-mean/standard_deviation
print(standardization)

[-0.91485422  0.08514578  1.08514578  2.08514578  3.08514578  4.08514578
  5.08514578  6.08514578  7.08514578  8.08514578]


In [32]:
#logical operations 

data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
print(data[data>5])
print(data[(data>=5) & (data<=8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
